name: Comment on artifact diff

on:
  workflow_run:
    workflows: ["pull-request"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Post comment
        uses: live-codes/pr-comment-from-artifact@v1
        # with:
        #   GITHUB_TOKEN: ${{ github.token }}