name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18
          - 20
          - 22
    uses: repobuddy/.github/.github/workflows/pnpm-build.yml@main
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
  code:
    uses: repobuddy/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest", "windows-latest"]'
      node-version: '[18, 20]'
  update-snapshot:
    runs-on: ubuntu-latest
    needs: code
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps chromium

      - run: pnpm build
      - run: pnpm test -- -u

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "test: update snapshot"