name: update-snapshot
on:
  workflow_dispatch:
    # inputs:
    #   ref:
    #     description: 'Branch or tag to run the workflow on'
    #     required: true
    #     default: 'main'

jobs:
  update-snapshot:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps chromium

      - name: Install Dependencies
        run: pnpm install

      - run: pnpm build
      - run: pnpm test -- -u

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "test: update snapshot"